apiVersion: v1
kind: Service
metadata: 
  name:  {{ .Release.Name }}
  labels:
    app: drupal
spec: 
  ports: 
    - 
      name: web
      port: 80
      protocol: TCP
      targetPort: 80
  selector: 
    app:  {{ .Release.Name }}
    tier: frontend
  type: LoadBalancer